export const ADD_TO_FAVORITES = "FAVS/ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "FAVS/REMOVE_FROM_FAVORITES"
export const FAV_SUCCESS = 'FAVS/SUCCESS';
export const FAV_FAILURE = 'FAVS/FAILURE';
export const FAV_LOADING = 'FAVS/LOADING'